services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app 
      - ./backend:/app/uploads
    depends_on:
      - db
    command: >
     sh -c "
     migrate -path /app/db/migrations -database 'postgres://postgres:password@db:5432/db?sslmode=disable' up &&
     go run main.go
     "
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - front_node_modules:/workspace/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  db:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
  front_node_modules:
  