services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app 
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
      - redis
    command: >
     sh -c "
     migrate -path /app/db/migrations -database 'postgres://postgres:password@db:5432/db?sslmode=disable' up &&
     go run main.go
     "
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - front_node_modules:/workspace/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  db:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db-store:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-store:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-store:
  front_node_modules:
  redis-store:
  