version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-watcher:
    image: alpine
    volumes:
      - ./scripts:/scripts
      - ./:/app
    command: >
      sh -c "apk add --no-cache postgresql-client bash &&
             while true; do
               /scripts/dump-db.sh;
               sleep 300;
             done"
    depends_on:
      - db

volumes:
  postgres_data: 