import { Noto_Sans_JP, Roboto, Tsukimi_Rounded } from "next/font/google";
import "@/app/styles/globals.scss";
import QueryProvider from "./providers/QueryProvider";
import LoadingProvider from "./providers/LoadingProvider";
import type { Metadata } from "next";
import Container from "@/app/components/layout/Container/Container";

const notoSansJp = Noto_Sans_JP({
  subsets: ["latin", "latin-ext"],
  weight: ["400", "700"],
  preload: false,
  variable: "--font-noto-sans-jp",
  display: "swap",
  fallback: ["sans-serif"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  preload: false,
  variable: "--font-roboto",
  display: "swap",
  fallback: ["Arial", "Helvetica", "sans-serif"],
});

const tsukimiRounded = Tsukimi_Rounded({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  preload: false,
  variable: "--font-tsukimi-rounded",
  display: "swap",
  fallback: ["Arial", "Helvetica", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ja"
      className={`${notoSansJp.variable} ${roboto.variable} ${tsukimiRounded.variable}`}
      suppressHydrationWarning
    >
      <head />
      <body>
        <QueryProvider>
          <LoadingProvider>
            <Container>{children}</Container>
          </LoadingProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
