name: Update Database

on:
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '17'
          postgresql db: 'postgres'
          postgresql user: 'postgres'
          postgresql password: 'password'

      - name: Dump local database
        run: |
          pg_dump -U postgres -h localhost -d postgres > dump.sql

      - name: Backup Supabase database
        run: |
          PGPASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }} pg_dump "postgresql://postgres.qmrjsqeigdkizkrpiahs:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres" --format=custom > backup.dump

      - name: Update Supabase database
        run: |
          PGPASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }} psql "postgresql://postgres.qmrjsqeigdkizkrpiahs:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres" -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public; CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\" SCHEMA public;"
          PGPASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }} psql "postgresql://postgres.qmrjsqeigdkizkrpiahs:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres" < dump.sql 