name: Update Database

on:
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '17'
          postgresql db: 'amarimono'
          postgresql user: 'postgres'
          postgresql password: 'password'

      - name: Dump local database
        run: |
          pg_dump -U postgres -h localhost -d amarimono > dump.sql

      - name: Backup Render database
        run: |
          PGPASSWORD=${{ secrets.RENDER_DB_PASSWORD }} pg_dump -h dpg-d04spp6uk2gs73e0qgrg-a.oregon-postgres.render.com -U amarimono_user -d amarimono --format=custom > backup.dump

      - name: Update Render database
        run: |
          PGPASSWORD=${{ secrets.RENDER_DB_PASSWORD }} psql "postgresql://amarimono_user@dpg-d04spp6uk2gs73e0qgrg-a.oregon-postgres.render.com/amarimono?sslmode=require" -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
          PGPASSWORD=${{ secrets.RENDER_DB_PASSWORD }} psql "postgresql://amarimono_user@dpg-d04spp6uk2gs73e0qgrg-a.oregon-postgres.render.com/amarimono?sslmode=require" < dump.sql 