name: Update Database

on:
  push:
    branches:
      - main
    paths:
      - 'dump.sql'

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL 17 client tools
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Set up PostgreSQL 17
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '17'
          postgresql db: 'postgres'
          postgresql user: 'postgres'
          postgresql password: 'postgres'

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            if PGPASSWORD=postgres psql -U postgres -h localhost -d postgres -c "SELECT 1" >/dev/null 2>&1; then
              echo "PostgreSQL is ready"
              exit 0
            fi
            echo "Waiting for PostgreSQL... ($i/10)"
            sleep 2
          done
          echo "PostgreSQL is not ready"
          exit 1

      - name: Dump local database
        run: |
          PGPASSWORD=postgres pg_dump -U postgres -h localhost -d postgres > dump.sql

      - name: Backup Supabase database
        run: |
          PGPASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }} pg_dump "postgresql://postgres.qmrjsqeigdkizkrpiahs:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres" --format=custom > backup.dump

      - name: Update Supabase database
        run: |
          PGPASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }} psql "postgresql://postgres.qmrjsqeigdkizkrpiahs:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres" -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public; CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\" SCHEMA public;"
          PGPASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }} psql "postgresql://postgres.qmrjsqeigdkizkrpiahs:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres" < dump.sql 